/**
 * DataInspector.tsx — Dataset Viewer Page
 * =========================================
 * Displays the generated training dataset for educational inspection.
 *
 * Features:
 *   - Board visualization of each recorded game state
 *   - Navigation slider to step through a game's state history
 *   - Metadata display: ground truth label, turn indicator, game result
 *   - Game selector dropdown (when multiple games exist)
 *
 * Data source: GET /api/dataset returns the JSON generated by self-play.
 * Each game contains a sequence of board states, all labeled with the outcome.
 */
import { useEffect, useState } from 'react';

interface GameState {
    board: number[][];
    turn: number;
    label: number;
}

export const DataInspector = () => {
    const [dataset, setDataset] = useState<any[]>([]);
    const [gameIdx, setGameIdx] = useState(0);
    const [moveIdx, setMoveIdx] = useState(0);
    const [loading, setLoading] = useState(true);
    const [error, setError] = useState<string | null>(null);

    useEffect(() => {
        const fetchDataset = async () => {
            try {
                const res = await fetch('http://localhost:8000/api/dataset');
                if (!res.ok) throw new Error('Failed to fetch dataset');
                const data = await res.json();
                setDataset(data.games || []);
            } catch (err: any) {
                setError(err.message);
            } finally {
                setLoading(false);
            }
        };
        fetchDataset();
    }, []);

    const currentGame = dataset[gameIdx];
    const currentHistory = currentGame?.history || [];
    const currentState: GameState | null = currentHistory[moveIdx] || null;
    const sampleBoard = currentState ? currentState.board : Array(8).fill(null).map(() => Array(8).fill(0));

    return (
        <div className="panel" style={{ maxWidth: '800px', margin: '0 auto' }}>
            <h2>Data Inspector</h2>
            <p style={{ color: 'var(--text-secondary)', marginBottom: '2rem' }}>
                Explore the spatial tensors generated by the Minimax engine. This helps students verify
                that the ground-truth labels backpropagated correctly.
            </p>

            {/* Example static UI structure for the inspector */}
            <div style={{ display: 'flex', gap: '2rem' }}>

                {/* State Visualizer */}
                <div style={{ flex: 1 }}>
                    <div style={{
                        width: '100%',
                        aspectRatio: '1',
                        border: '2px solid var(--glass-border)',
                        display: 'grid',
                        gridTemplateColumns: 'repeat(8, 1fr)'
                    }}>
                        {sampleBoard.map((row, r) =>
                            row.map((val, c) => (
                                <div key={`${r}-${c}`} style={{
                                    backgroundColor: (r + c) % 2 === 1 ? 'var(--board-dark)' : 'var(--board-light)',
                                    display: 'flex', justifyContent: 'center', alignItems: 'center'
                                }}>
                                    {val !== 0 && (
                                        <div style={{
                                            width: '70%', height: '70%', borderRadius: '50%',
                                            backgroundColor: (val === 1 || val === 3) ? 'var(--piece-red)' : 'var(--piece-white)',
                                            border: val === 3 || val === 4 ? '2px solid gold' : 'none',
                                            display: 'flex', justifyContent: 'center', alignItems: 'center'
                                        }}>
                                            {(val === 3 || val === 4) && <span style={{ color: 'gold', fontSize: '1rem', fontWeight: 'bold' }}>K</span>}
                                        </div>
                                    )}
                                </div>
                            ))
                        )}
                    </div>

                    {/* Pagination */}
                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '1rem', alignItems: 'center' }}>
                        <button
                            className="secondary"
                            disabled={moveIdx === 0}
                            onClick={() => setMoveIdx(m => Math.max(0, m - 1))}
                        >&larr; Prev Move</button>
                        <span>Move {moveIdx + 1} / {currentHistory.length || 0}</span>
                        <button
                            className="secondary"
                            disabled={moveIdx >= currentHistory.length - 1}
                            onClick={() => setMoveIdx(m => Math.min(currentHistory.length - 1, m + 1))}
                        >Next Move &rarr;</button>
                    </div>

                    <div style={{ display: 'flex', justifyContent: 'space-between', marginTop: '1rem', alignItems: 'center', borderTop: '1px solid var(--glass-border)', paddingTop: '1rem' }}>
                        <button
                            className="secondary"
                            disabled={gameIdx === 0}
                            onClick={() => { setGameIdx(g => Math.max(0, g - 1)); setMoveIdx(0); }}
                        >&larr; Prev Game</button>
                        <span>Game {gameIdx + 1} / {dataset.length}</span>
                        <button
                            className="secondary"
                            disabled={gameIdx >= dataset.length - 1}
                            onClick={() => { setGameIdx(g => Math.min(dataset.length - 1, g + 1)); setMoveIdx(0); }}
                        >Next Game &rarr;</button>
                    </div>
                </div>

                {/* Info Panel */}
                <div style={{ flex: 1 }}>
                    <div className="edu-note" style={{ margin: 0, height: '100%' }}>
                        <h3 style={{ fontSize: '1.1rem', color: 'var(--text-primary)', marginBottom: '1rem' }}>Tensor Data</h3>

                        <div style={{ marginBottom: '1rem' }}>
                            <strong style={{ color: 'var(--accent-blue)' }}>Label (Ground Truth):</strong><br />
                            {loading ? "Loading..." : error ? "Error loading" : dataset.length === 0 ? "No dataset found. Generate some games first!" : currentState ? (
                                currentState.label === 1.0 ? "1.0 (Red Win)" :
                                    currentState.label === 0.0 ? "0.0 (White Win)" : "0.5 (Draw)"
                            ) : "N/A"}
                            <br /><br />
                            <strong style={{ color: 'var(--accent-green)' }}>Turn to move:</strong> {currentState ? (currentState.turn === 1 ? 'Red' : 'White') : "N/A"}
                        </div>

                        <div>
                            <strong style={{ color: 'var(--accent-purple)' }}>Current Turn Tensor:</strong><br />
                            [ {currentState ? (currentState.turn === 1 ? '1, 1, 1, 1, 1, ...' : '0, 0, 0, 0, 0, ...') : 'N/A'} ] <br />
                            <em style={{ fontSize: '0.8rem' }}>(Channel 5 logic)</em>
                        </div>

                        <p style={{ marginTop: '2rem', fontSize: '0.85rem' }}>
                            This view reads directly from the generated <code>dataset.json</code> file, parsing the list of lists into visual representations.
                        </p>
                    </div>
                </div>

            </div>
        </div>
    );
};
