import pytorch_lightning as pl
import torch
import torch.nn.functional as F
from torch.utils.data import DataLoader, Dataset
import json
from backend.model.cnn import TwoHeadedCNN, board_to_tensor
from backend.engine.board import CheckersBoard

class CheckersDataset(Dataset):
    """
    In-memory dataset loaded from the JSON generated by generator.py.
    """
    def __init__(self, json_file: str):
        with open(json_file, 'r') as f:
            data = json.load(f)
            
        self.samples = []
        for game in data:
            # We want to train on each board state -> output probability
            # The label is the same for the whole history in basic self-play backprop
            label = game.get('history', [{}])[0].get('label', 0.5) if game.get('history') else 0.5
            
            for state in game.get('history', []):
                board_grid = state['board']
                turn = state['turn']
                
                # Convert the board to our 5-channel tensor
                tensor = board_to_tensor(board_grid, turn)
                
                # Our targets: [Prob Black Wins, Prob White Wins]
                # If label == 1.0 (Black Win): [1.0, 0.0]
                # If label == 0.0 (White Win): [0.0, 1.0]
                # If label == 0.5 (Draw): [0.5, 0.5] (Approximation for MSE if needed, though we use BCE)
                
                target_black = float(label)
                target_white = 1.0 - float(label)
                if target_black == 0.5:
                    target_white = 0.5
                    
                target = torch.tensor([target_black, target_white], dtype=torch.float32)
                self.samples.append((tensor, target))

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        return self.samples[idx]


class CheckersLightningModule(pl.LightningModule):
    """
    PyTorch Lightning wrapper for training the TwoHeadedCNN.
    Handles optimization, training steps, and validation steps.
    """
    def __init__(self, learning_rate: float = 1e-3, channels: int = 5, hidden_dims: int = 64,
                 num_conv_layers: int = 2, dropout_rate: float = 0.2):
        super().__init__()
        self.save_hyperparameters()
        self.model = TwoHeadedCNN(
            channels=channels, hidden_dims=hidden_dims,
            num_conv_layers=num_conv_layers, dropout_rate=dropout_rate
        )
        self.learning_rate = learning_rate

    def forward(self, x):
        return self.model(x)

    def _shared_step(self, batch, batch_idx, phase: str):
        x, y = batch
        # Forward pass
        p_black, p_white = self(x)
        
        # y is shape (Batch, 2). y[:, 0] is black target, y[:, 1] is white target
        target_black = y[:, 0]
        target_white = y[:, 1]
        
        # Binary Cross Entropy Loss for each head
        loss_black = F.binary_cross_entropy(p_black, target_black)
        loss_white = F.binary_cross_entropy(p_white, target_white)
        
        # Total loss is the sum of both heads
        loss = loss_black + loss_white
        
        self.log(f"{phase}_loss", loss, prog_bar=True, on_step=False, on_epoch=True)
        self.log(f"{phase}_loss_black", loss_black, on_step=False, on_epoch=True)
        self.log(f"{phase}_loss_white", loss_white, on_step=False, on_epoch=True)
        
        return loss

    def training_step(self, batch, batch_idx):
        return self._shared_step(batch, batch_idx, "train")

    def validation_step(self, batch, batch_idx):
        return self._shared_step(batch, batch_idx, "val")

    def configure_optimizers(self):
        # Adam optimizer is generally robust for this shallow CNN
        optimizer = torch.optim.Adam(self.parameters(), lr=self.learning_rate)
        return optimizer
